# Generated by Django 6.1.1 on 2026-09-09 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_alter_category_options_alter_category_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='category_id',
        ),
    ]
